# Generated by Django 5.2.7 on 2025-11-26 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=20)),
                ('sunat_id', models.CharField(blank=True, help_text='ID que SUNAT devuelve (ej: 675c532840264100151a3644)', max_length=100, null=True, unique=True)),
                ('sunat_status', models.CharField(blank=True, help_text='Estado de SUNAT: ACEPTADO, RECHAZADO, EXCEPCION', max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('exception', 'Excepción'), ('failed', 'Fallido')], default='processing', max_length=20)),
                ('xml_url', models.URLField(blank=True, help_text='URL del XML en CDN de SUNAT', max_length=500, null=True)),
                ('cdr_url', models.URLField(blank=True, help_text='URL del CDR en CDN de SUNAT', max_length=500, null=True)),
                ('sunat_issue_time', models.BigIntegerField(blank=True, help_text='Timestamp Unix de emisión (de SUNAT)', null=True)),
                ('sunat_response_time', models.BigIntegerField(blank=True, help_text='Timestamp Unix de respuesta (de SUNAT)', null=True)),
                ('production', models.BooleanField(default=False)),
                ('is_purchase', models.BooleanField(default=False)),
                ('faults', models.JSONField(blank=True, help_text='Errores de SUNAT si los hay', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error interno si falló', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto total (del request o parseado del XML)', max_digits=10, null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='PDF generado y almacenado en R2', null=True, upload_to='sunat_documents/pdf/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
