# Generated by Django 5.2.7 on 2025-11-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='serie',
            field=models.CharField(max_length=20),
        ),
    ]
