# Generated by Django 5.2.7 on 2025-10-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_address_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IP', 'In Progress'), ('IK', 'In Kitchen'), ('PA', 'Packing'), ('HA', 'Handed'), ('IT', 'In Transit'), ('DO', 'Delivered'), ('CA', 'Cancelled')], default='IP', max_length=2),
        ),
    ]
