# Generated by Django 5.2.7 on 2025-10-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('T', 'Table'), ('D', 'Delivery'), ('G', 'To Go')], default='G', max_length=2),
        ),
    ]
