# Generated by Django 5.2.7 on 2025-11-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_account_category_is_menu_category_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('I', 'Income'), ('E', 'Expense')], max_length=10),
        ),
    ]
