# Generated by Django 5.2.7 on 2025-11-28 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_transaction_transaction_type'),
        ('taxes', '0002_alter_document_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxes.document'),
        ),
    ]
