# Generated by Django 5.2.7 on 2025-11-30 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_document'),
        ('taxes', '0002_alter_document_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxes.document'),
        ),
    ]
