# Generated by Django 5.2.7 on 2025-12-08 13:12

import store.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=store.storage.R2Storage(), upload_to='dishes/'),
        ),
    ]
