# Generated by Django 5.2.7 on 2025-12-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('DC', 'Debit Card'), ('CC', 'Credit Card'), ('VW', 'Virtual Wallet'), ('OT', 'Otro')], default='VW', max_length=2),
        ),
    ]
