# Generated by Django 5.2.7 on 2026-06-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_topping_saletopping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('INGREDIENT', 'Ingredient'), ('PACKAGING', 'Packaging'), ('OTHER', 'Other')], default='INGREDIENT', max_length=10),
        ),
    ]
