# Generated by Django 5.2.7 on 2026-06-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('INGREDIENT', 'I'), ('OTHER', 'O')], default='INGREDIENT', max_length=10),
        ),
    ]
