FROM nginx
RUN echo "Starting nginx dockerfile"
RUN mkdir -p /var/www/certbot
# RUN mkdir -p /vol/web/static

# COPY ./app/amauta/staticfiles/ /vol/web/static/
# COPY ./nginx.conf /etc/nginx/nginx.conf
